-keep class com.opensolr.photos.sync.SyncWorker { <init>(...); }
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**
-dontwarn org.osmdroid.**
-keep class com.opensolr.photos.sync.FaceWorker { <init>(...); }
-keep class org.tensorflow.lite.** { *; }
